
version: 2.1


jobs:
  build-and-test: 
      parameters:
        version:
          type: string
      machine:
        image: ubuntu-2004:202111-01
    
      steps:
        - checkout
        - run: pyenv install -v << parameters.version >>; pyenv global << parameters.version >>; pip install invoke; pip install cleo importlib_metadata;  wget -q -O - "$@" https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -; export PATH=$PATH:/$HOME/bin:/$HOME/.poetry/bin; poetry config virtualenvs.create false; invoke installdeps --dev; invoke test;


workflows:
  test_project: 
    jobs:
      - build-and-test: 
          matrix:
            parameters:
              version: ["3.7.0", "3.8.0", "3.9.0"]
