# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  build-and-test: 
      parameters:
        version:
          type: string
      machine:
        image: ubuntu-2004:202111-01
    
      steps:
        - checkout
        #- run: pyenv install --list 
        - run: pyenv install -v << parameters.version >>; pyenv global << parameters.version >>; pip install invoke;  pip install poetry; export PATH=$PATH:/$HOME/bin:/$HOME/.poetry/bin; invoke installdeps --dev; 

# Invoke jobs via workflows
workflows:
  test_project: # This is the name of the workflow, feel free to change it to better match your workflow.
    # jobs you want to run.
    jobs:
      - build-and-test: 
          matrix:
            parameters:
              version: ["3.7.0", "3.10.0"]
