# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  build-and-test: 
    machine:
      image: ubuntu-2004:202111-01
    
    steps:
      - checkout
      - run: pip3 install invoke
      - run: wget -q -O - "$@" https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - run: export PATH=$PATH:/home/bin:/home/.poetry/bin
      - run: poetry config virtualenvs.create false
      - run: invoke installdeps --dev

# Invoke jobs via workflows
workflows:
  test_docker: # This is the name of the workflow, feel free to change it to better match your workflow.
    # jobs you want to run.
    jobs:
      - build-and-test
